/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package br.senai.sp.jandira.ui;

import br.senai.sp.jandira.dao.PlanoDeSaudeDAO;
import br.senai.sp.jandira.model.PlanosDeSaude;
import br.senai.sp.jandira.model.TipoOperacao;
import javax.swing.JOptionPane;

/**
 *
 * @author 22282115
 */
public class DialogPlanosDeSaude extends javax.swing.JDialog {

    private TipoOperacao tipoOperacao;
    private PlanosDeSaude planoDeSaude;

    public DialogPlanosDeSaude(
            java.awt.Frame parent,
            boolean modal,
            TipoOperacao tipoOperacao,
            PlanosDeSaude planoDeSaude
    ) {
        super(parent, modal);
        initComponents();
        this.tipoOperacao = tipoOperacao;
        this.planoDeSaude = planoDeSaude;

        // Preencher os campos, caso o tipo de operação for ALTERAR
        if (tipoOperacao == tipoOperacao.ALTERAR) {
            preencherFormulario();
        }

    }

    private void preencherFormulario() {
        tituloLabel.setText("Plano de Saúde - " + tipoOperacao);
        LabelIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/img/edit.png")));
        textFieldCodigo.setText(planoDeSaude.getCodigo().toString());
        textFieldNomeDaOperadora.setText(planoDeSaude.getOperadora());
        textFieldTipoDoPlano.setText(planoDeSaude.getTipoDoPlano());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LabelIcon = new javax.swing.JLabel();
        tituloLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        textFieldTipoDoPlano = new javax.swing.JTextField();
        textFieldNomeDaOperadora = new javax.swing.JTextField();
        textFieldCodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        buttonSalvar = new javax.swing.JButton();
        buttonCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Adicionar");
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(155, 155, 155));
        jPanel1.setLayout(null);

        LabelIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/img/adicionar-ficheiro.png"))); // NOI18N
        jPanel1.add(LabelIcon);
        LabelIcon.setBounds(50, 10, 30, 40);

        tituloLabel.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        tituloLabel.setText("Planos de Saude - ADICIONAR");
        jPanel1.add(tituloLabel);
        tituloLabel.setBounds(90, 30, 660, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 790, 90);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Detalhes do Plano de Saúde:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Monospaced", 1, 18), new java.awt.Color(155, 155, 155))); // NOI18N
        jPanel2.setLayout(null);

        textFieldTipoDoPlano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldTipoDoPlanoActionPerformed(evt);
            }
        });
        jPanel2.add(textFieldTipoDoPlano);
        textFieldTipoDoPlano.setBounds(40, 190, 280, 30);
        jPanel2.add(textFieldNomeDaOperadora);
        textFieldNomeDaOperadora.setBounds(40, 130, 280, 30);

        textFieldCodigo.setEditable(false);
        jPanel2.add(textFieldCodigo);
        textFieldCodigo.setBounds(40, 70, 80, 30);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Tipo do Plano:");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(40, 170, 130, 20);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Nome da Operadora:");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(40, 110, 160, 20);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("Código:");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(40, 50, 70, 20);

        buttonSalvar.setBackground(new java.awt.Color(248, 248, 248));
        buttonSalvar.setForeground(new java.awt.Color(248, 248, 248));
        buttonSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/img/salve-.png"))); // NOI18N
        buttonSalvar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buttonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSalvarActionPerformed(evt);
            }
        });
        jPanel2.add(buttonSalvar);
        buttonSalvar.setBounds(650, 200, 90, 60);

        buttonCancelar.setBackground(new java.awt.Color(248, 248, 248));
        buttonCancelar.setForeground(new java.awt.Color(248, 248, 248));
        buttonCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/img/cancelar_1.png"))); // NOI18N
        buttonCancelar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buttonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelarActionPerformed(evt);
            }
        });
        jPanel2.add(buttonCancelar);
        buttonCancelar.setBounds(650, 270, 90, 60);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(20, 110, 750, 360);

        setBounds(0, 0, 805, 528);
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldTipoDoPlanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldTipoDoPlanoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldTipoDoPlanoActionPerformed

    private void buttonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelarActionPerformed

        dispose();

    }//GEN-LAST:event_buttonCancelarActionPerformed

    private void buttonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSalvarActionPerformed

        if (tipoOperacao == tipoOperacao.ADICIONAR) {
            gravar();
        } else {
            atualizar();
        }

    }//GEN-LAST:event_buttonSalvarActionPerformed

    private void gravar() {
        // Criar um objeto plano de saúde
        PlanosDeSaude planoDeSaude = new PlanosDeSaude();
        planoDeSaude.setOperadora(textFieldNomeDaOperadora.getText());
        planoDeSaude.setTipoDoPlano(textFieldTipoDoPlano.getText());

        if (validarCadastro()) {
            PlanoDeSaudeDAO.gravar(planoDeSaude);
            JOptionPane.showMessageDialog(
                    this,
                    "Plano de saúde gravado com sucesso!",
                    "Plano de Saúde",
                    JOptionPane.INFORMATION_MESSAGE);
            dispose();
        }
    }
    
    private void atualizar(){
        if(validarCadastro()){
        planoDeSaude.setOperadora(textFieldNomeDaOperadora.getText());
        planoDeSaude.setTipoDoPlano(textFieldTipoDoPlano.getText());
        PlanoDeSaudeDAO.atualizar(planoDeSaude);
        JOptionPane.showMessageDialog(
                    this,
                    "Plano de saúde atualizado com sucesso!",
                    "Plano de Saúde",
                    JOptionPane.INFORMATION_MESSAGE);
        dispose();
        }
    }

    private boolean validarCadastro() {
        if (textFieldNomeDaOperadora.getText().isEmpty()) {
            JOptionPane.showMessageDialog(
                    this,
                    "Por favor preencha o nome da operadora!",
                    "Plano de Saúde",
                    JOptionPane.ERROR_MESSAGE);
            textFieldNomeDaOperadora.requestFocus();
            return false;
        }
        if (textFieldTipoDoPlano.getText().isEmpty()) {
            JOptionPane.showMessageDialog(
                    this,
                    "Por favor preencha o tipo do plano!",
                    "Plano de Saúde",
                    JOptionPane.ERROR_MESSAGE);
            textFieldTipoDoPlano.requestFocus();
            return false;
        }
        return true;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelIcon;
    private javax.swing.JButton buttonCancelar;
    private javax.swing.JButton buttonSalvar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField textFieldCodigo;
    private javax.swing.JTextField textFieldNomeDaOperadora;
    private javax.swing.JTextField textFieldTipoDoPlano;
    private javax.swing.JLabel tituloLabel;
    // End of variables declaration//GEN-END:variables
}
